# .NET Testing Workflow
name: Test .NET Libraries

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'Docs/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.x'
  BUILD_CONFIGURATION: 'Debug'

jobs:
  test-windows:
    name: 'Windows'
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ServiceNow.NET.sln

      - name: Build solution
        run: dotnet build ServiceNow.NET.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run tests
        run: >-
          dotnet test ServiceNow.NET.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal
          --logger trx --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-windows
          path: '**/*.trx'

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports-windows
          path: '**/coverage.cobertura.xml'

  test-linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ServiceNow.NET.sln

      - name: Build solution
        run: dotnet build ServiceNow.NET.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run tests
        run: >-
          dotnet test ServiceNow.NET.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal
          --logger trx --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-linux
          path: '**/*.trx'

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports-linux
          path: '**/coverage.cobertura.xml'

  test-macos:
    name: 'macOS'
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ServiceNow.NET.sln

      - name: Build solution
        run: dotnet build ServiceNow.NET.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Run tests
        run: >-
          dotnet test ServiceNow.NET.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal
          --logger trx --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-macos
          path: '**/*.trx'

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports-macos
          path: '**/coverage.cobertura.xml'

